### ISSUE TITLE
reident_tools package

### ISSUE THREAD

**Issue by sidify** [opendp/smartnoise-samples#113]
I am trying to recreate this notebook : https://github.com/opendp/smartnoise-samples/blob/master/whitepaper-demos/2-reidentification-attack.ipynb

I donot find the package `reident_tools`, can somebody point me where to find it? 
`import reident_tools as reident`

Thank you.

**Comment by Shoeboxam** [comment]
Hi @sidify, you must have pulled that one reidentification .ipynb file down, and missed the adjacent `reident_tools.py`. [See here!](https://github.com/opendp/smartnoise-samples/blob/master/whitepaper-demos/reident_tools.py)

Let me know if you run into any other issues!

**Comment by sidify** [comment]
Thank you. Closing the issue :)
