### ISSUE TITLE
SQL queries notebook bug

### ISSUE THREAD

**Issue by globusharris** [opendp/smartnoise-samples#48]
Damien Desfontaines found error in the SQL queries notebook:

![error](https://user-images.githubusercontent.com/20525757/82468518-e1a6e200-9a90-11ea-9c67-2e7b44d1f245.png)

**Comment by globusharris** [comment]
https://twitter.com/TedOnPrivacy/status/1263453728394395649 see thread for some debugging of this by him

**Comment by raprasad** [comment]
@eedeleon: flagging this, may be old
