### ISSUE TITLE
data/README.md is out of date

### ISSUE THREAD

**Issue by huwd** [opendp/smartnoise-samples#82]
Hello,

I've been stepping through your data/README.md to better understand the codebase and I've noticed a couple of places it's out of date.

It doesn't seem you are accepting PRs from the public, so I thought I'd flag them here and perhaps put up a couple of patches if that helps:

Things i've spotted that are amiss:
- [ ] PrivateReader now takes reader first and meta second
- [ ] PandasReader now takes reader first and meta second
- [ ] PrivateReader no longer had an `execute_typed` method

**Comment by huwd** [comment]
patch for PandasReader:

[0001-Update-README-to-swap-PandasReader-params-order.txt](https://github.com/opendp/smartnoise-samples/files/6304542/0001-Update-README-to-swap-PandasReader-params-order.txt)

**Comment by huwd** [comment]
patch for PrivateReader

[0002-Update-README-to-swap-PrivateReader-params-order.txt](https://github.com/opendp/smartnoise-samples/files/6304544/0002-Update-README-to-swap-PrivateReader-params-order.txt)

**Comment by huwd** [comment]
The [README.md ](https://github.com/opendp/smartnoise-samples/tree/master/data#sql-data-access)also shows three instances of `private_reader.execute_typed(query)`

This throws errors saying that PrivateReader does not have an `execute_typed` method.
I suspect this might have been removed and consolidated into [execute](https://github.com/opendp/smartnoise-sdk/blob/main/sdk/opendp/smartnoise/sql/private_reader.py#L164), is that right?

When I swap that line out in the docs everything works 🎉 .

Let me know if I've understood correctly, if a patch is helpful would be happy to offer another or a PR?

Your work here is really interesting and we'd like to have more of a play around, I'd be happy to amend any docs I find have slipped out of date whilst we're going through?

**Comment by huwd** [comment]
Ah ha, apologies not done masses of open source stuff before - clearly forking and making a PR is the approach here!
So i've done that.

**Comment by raprasad** [comment]
@huwd: Thank you. We appreciate all of the comments and the PR. We should be up to date by end of next week--including the requirements.txt file and several notebooks.

**Comment by huwd** [comment]
Oh fantastic thank you!
Shout if this is a duplicate I'd be happy to close these down?
